Strip compiler executables and minor fixes
abhiTronix/raspberry-pi-cross-compilers pull request #63
Opened 2021-02-03 09:28 UTC by visglz

* Strip on compiler install (#39)
    * This drastically reduces extracted size from 1.7GB to 477MB
* Followup to pull request #62
    * Set "set -eo pipefail" at top of script. Set "set -v" only for verbose
      mode
    * Fix wget download of linux kernel
        * The out wget was failing because of multiple lines. Only consider
          topmost line with most recent file)

2021-02-03 18:33 UTC, abhiTronix requested changes
@visglz See line: https://github.com/abhiTronix/raspberry-pi-cross-compilers/blob/5f9984748a9e4e7c17cfc25b6f244215ac3406b9/build-scripts/RTBuilder_64b#L64

Kindly remove it or remove your patch. It is a default behavior if verbose flag is not defined.

2021-02-04 07:39 UTC, visglz commented
> @visglz See line:
> 
> https://github.com/abhiTronix/raspberry-pi-cross-compilers/blob/5f9984748a9e4e7c17cfc25b6f244215ac3406b9/build-scripts/RTBuilder_64b#L64
> 
> Kindly remove it or remove your patch. It is a default behavior if verbose flag is not defined.

Done

2021-02-04 12:27 UTC, abhiTronix commented
@visglz Approved. Thank you for your contribution.

2021-02-04 12:27 UTC, abhiTronix approved these changes

2021-02-04 12:31 UTC, abhiTronix commented
@visglz Do we need strip command for native binaries as they already sized around 100mb? Also can please you test native binaries on raspberry if available?

2021-02-04 12:32 UTC, abhiTronix commented
@visglz I might remove strip from native binaries. Thanks for this contribution, Much appreciated. 🎉

2021-02-04 12:33 UTC, merged